server:
  port: 8110
  
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:PersonalInfoDB
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
